DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;
USE burger_db;
USE JAWSDB;

CREATE TABLE burgers (
	id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    burger_name VARCHAR(255) NOT NULL,
    devoured BOOLEAN,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);